### ISSUE TITLE
CSD3 files missing for new rds folders

### ISSUE THREAD

**Issue by LariDG** [ukaea/fair-mast-ingestion#19]
Project folder being changed meaning correct files need to be changed over. 
uda-ssl.sh has been added to directory:

~/rds/rds-ukaea-ap002-mOlK9qn0PlQ/fairmast/uda-ssl.sh

but within uda-ssl.sh a file .uda is called which has not been added to the new directory.
Hence, .uda needs to be moved and the line:
SSL_HOME="$HOME/rds/rds-ukaea-mast-sPGbyCAPsJI/.uda" 
needs to be changed to its new location.

Files to be added:

- $HOME/rds/rds-ukaea-ap002-mOlK9qn0PlQ/fairmast/.uda
- /rds/project/rds-mOlK9qn0PlQ/fairmast/local_cache/
- /rds/project/rds-mOlK9qn0PlQ/fairmast/data/uda

Files to be changed:

- uda-ssl.sh :
    -- SSL_HOME="$HOME/rds/rds-ukaea-mast-sPGbyCAPsJI/.uda" >> 
         SSL_HOME="$HOME/rds/rds-ukaea-ap002-mOlK9qn0PlQ/fairmast/.uda"

**Comment by LariDG** [comment]
Linked to issue #20, see script changes to confirm file destination changes

**Comment by NathanCummings** [comment]
Moving things over now. I'll let you know when it is done. I've also made the edit to `uda-ssl.sh`.

**Comment by NathanCummings** [comment]
This is done now.
